/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compi;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class tablas extends javax.swing.JFrame {

   ArrayList<String> ERR_SINTAXIS = new ArrayList<String>();
    ArrayList<String> simbolos = new ArrayList<String>();
    ArrayList<String> ERR_SEMANTICOS = new ArrayList<String>();
     DefaultTableModel modelo_sint, modelo_simbolos,modelo_sema;
     
    public tablas() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
        public void llenar_tabla_sintax(ArrayList<String> er_sint){
        try{
           this.ERR_SINTAXIS = er_sint;
    modelo_sint =  (DefaultTableModel) this.TAB_LEX_SINT.getModel();
        for (int i = 0; i < ERR_SINTAXIS.size(); i++) {
            String arre [] = ERR_SINTAXIS.get(i).split(",");
            if (arre[1].equals("0")) { arre[1]="final"; }
            modelo_sint.addRow(arre);
        }
    this.TAB_LEX_SINT.setModel(modelo_sint);
        }catch(NullPointerException e){}
    }
    
    public void llenar_tab_sim(ArrayList<String> sim){
    this.simbolos = sim;
     modelo_simbolos =  (DefaultTableModel) this.TAB_SIM.getModel();
        for (int i = 0; i < simbolos.size(); i++) {
            String arre [] = simbolos.get(i).split(",");
            modelo_simbolos.addRow(arre);
        }
    this.TAB_SIM.setModel(modelo_simbolos);
    }
    
    public void llenar_tab_ERR(ArrayList<String> ERR){
    this.ERR_SEMANTICOS = ERR; 
    modelo_sema = (DefaultTableModel) this.TAB_SEM.getModel();
   
    for (int i = 0; i < ERR_SEMANTICOS.size(); i++) {
            String arre [] = ERR_SEMANTICOS.get(i).split(",");
           if (arre[2].equals("0")) { arre[2]="final"; }
            modelo_sema.addRow(arre); 

        }
     TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(modelo_sema);
    this.TAB_SEM.setModel(modelo_sema);
     TAB_SEM.setRowSorter(elQueOrdena); //ORDENAMOS DE MAYOR A MENOR DEPENDIENDO LA COLUMNA SELECCIONADA
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        TAB_ERR_DESC = new javax.swing.JTable();
        TAB_DESCR = new javax.swing.JLabel();
        ETI_TAB_SIM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAB_SIM = new javax.swing.JTable();
        ETI_ERR_SEMA = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAB_SEM = new javax.swing.JTable();
        ETI_ERR_LEX_SIN = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAB_LEX_SINT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TAB_ERR_DESC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"E001", "ERROR DE SINTAXIS"},
                {"E002", "TOKEN NO VALIDO"},
                {"E003", "ID NO DECLARADO"},
                {"E004", "ID NO PUEDE SER PALABRA RESERV"},
                {"E005", "TIPOS NO COINCIDEN"},
                {"E006", "FALTA CERRAR LLAVE"},
                {"E007", "ID DUPLICADO"},
                {"E008", "OPERADOR ARITMETICO INCORRECTO"}
            },
            new String [] {
                "CLAVE_ERROR", "DESCRIPCION"
            }
        ));
        jScrollPane4.setViewportView(TAB_ERR_DESC);

        TAB_DESCR.setText("TAB_ERR_DESCRIPCION");

        ETI_TAB_SIM.setText("TABLA SIMBOLOS");

        TAB_SIM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO", "NOMBRE", "LINEA"
            }
        ));
        jScrollPane1.setViewportView(TAB_SIM);

        ETI_ERR_SEMA.setText("TABLA DE ERRORES GENERALES");

        TAB_SEM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ERROR ", "LINEA", "COLUMNA(token)"
            }
        ));
        jScrollPane2.setViewportView(TAB_SEM);

        ETI_ERR_LEX_SIN.setText("TABLA ERRORES  LEXICO SINTAXIS");

        TAB_LEX_SINT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LINEA", "COLUMNA(token)", "DESCRIPCION"
            }
        ));
        jScrollPane3.setViewportView(TAB_LEX_SINT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(TAB_DESCR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ETI_TAB_SIM, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(ETI_ERR_SEMA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ETI_ERR_LEX_SIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAB_DESCR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ETI_TAB_SIM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ETI_ERR_SEMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ETI_ERR_LEX_SIN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ETI_ERR_LEX_SIN;
    private javax.swing.JLabel ETI_ERR_SEMA;
    private javax.swing.JLabel ETI_TAB_SIM;
    private javax.swing.JLabel TAB_DESCR;
    private javax.swing.JTable TAB_ERR_DESC;
    private javax.swing.JTable TAB_LEX_SINT;
    private javax.swing.JTable TAB_SEM;
    private javax.swing.JTable TAB_SIM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
